# Generated by Django 6.1 on 2026-09-02 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_phone', models.CharField(max_length=10)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=30)),
                ('problem_description', models.TextField(max_length=200)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='mechanics.mechanic')),
            ],
        ),
    ]
