# Generated by Django 6.1 on 2026-09-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanic',
            old_name='service',
            new_name='services',
        ),
    ]
